# Cloud Build configuration for Gmail Calendar Sync
steps:
  # Debug step - show available variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      echo "PROJECT_ID: $PROJECT_ID"
      echo "SHORT_SHA: $SHORT_SHA"
      echo "COMMIT_SHA: $COMMIT_SHA"
      echo "BUILD_ID: $BUILD_ID"
      echo "_ARTIFACT_REGISTRY_URL: ${_ARTIFACT_REGISTRY_URL}"

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_ARTIFACT_REGISTRY_URL}/gmail-calendar-sync:$SHORT_SHA', '--progress=plain', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_ARTIFACT_REGISTRY_URL}/gmail-calendar-sync:$SHORT_SHA']

  # Deploy container image to Cloud Run Jobs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      # Get the current service account (CI用のサービスアカウント)
      CURRENT_SA=$$(gcloud config get-value account)
      echo "Using service account: $$CURRENT_SA"

      # Check if job exists and create or update accordingly
      if gcloud run jobs describe gmail-calendar-sync-job --region=asia-northeast1 > /dev/null 2>&1; then
        echo "Job exists, updating..."
        gcloud run jobs update gmail-calendar-sync-job \
          --image=${_ARTIFACT_REGISTRY_URL}/gmail-calendar-sync:$SHORT_SHA \
          --region=asia-northeast1 \
          --service-account=$$CURRENT_SA \
          --memory=512Mi \
          --cpu=1 \
          --task-timeout=900 \
          --parallelism=1 \
          --set-env-vars=LOG_LEVEL=INFO,SYNC_PERIOD_HOURS=8,PROJECT_ID=${PROJECT_ID} \
          --set-secrets=GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,GOOGLE_REFRESH_TOKEN=GOOGLE_REFRESH_TOKEN:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,SLACK_WEBHOOK_URL=SLACK_WEBHOOK_URL:latest
      else
        echo "Job does not exist, creating..."
        gcloud run jobs create gmail-calendar-sync-job \
          --image=${_ARTIFACT_REGISTRY_URL}/gmail-calendar-sync:$SHORT_SHA \
          --region=asia-northeast1 \
          --service-account=$$CURRENT_SA \
          --memory=512Mi \
          --cpu=1 \
          --task-timeout=900 \
          --parallelism=1 \
          --set-env-vars=LOG_LEVEL=INFO,SYNC_PERIOD_HOURS=8,PROJECT_ID=${PROJECT_ID} \
          --set-secrets=GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,GOOGLE_REFRESH_TOKEN=GOOGLE_REFRESH_TOKEN:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,SLACK_WEBHOOK_URL=SLACK_WEBHOOK_URL:latest
      fi

images:
  - '${_ARTIFACT_REGISTRY_URL}/gmail-calendar-sync:$SHORT_SHA'

# Substitution variables
substitutions:
  _ARTIFACT_REGISTRY_URL: 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/gmail-calendar-sync'

options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
