name: Security Audit

on:
  schedule:
    - cron: '0 3 * * 1'  # Weekly on Monday at 3 AM JST
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Add security scanning tools
        run: |
          uv add --group dev safety bandit[toml]

      - name: Run safety dependency vulnerability scan
        run: |
          uv run safety check --json --output safety-report.json || true
          echo "Safety scan completed"

      - name: Run bandit security linter
        run: |
          uv run bandit -r src/ -f sarif -o bandit-report.sarif || true
          uv run bandit -r src/ -f txt || true
          echo "Bandit scan completed"

      - name: Upload bandit SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: bandit-report.sarif
        continue-on-error: true

      - name: Create security summary
        if: always()
        run: |
          echo "## 🔒 Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Safety dependency scan completed" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Bandit security linter completed" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Results uploaded to GitHub Security tab" >> $GITHUB_STEP_SUMMARY
